import profileImg from '../src/images/profile-img.png'
const nfts = [
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '1',
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Qais',
    token_id: '2',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Rizwan',
    token_id: '3',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '4',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '5',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '6',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '7',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '8',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '9',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '10',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '11',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '12',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '13',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '14',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '15',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '16',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '17',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '18',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '19',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
  {
    provider: 'Wizardium',
    currentOwner: 'Saqi',
    name: 'Markus',
    token_id: '20',
    price: 299,
    img: profileImg,
    description:
      'Young alchemist and a great explorer. Fortune smiles at him, he always finds rich loot.',
    property: [
      ['Energy', '50'],
      ['Grade', 'Low'],
      ['Health', '50'],
      ['Luck', '1.2'],
      ['Type', 'Cat'],
    ],
  },
]
export default nfts
